#!/usr/bin/awk -f

BEGIN{

n=0
cmd="head "ARGV[1]
while(cmd|getline){
n++
if(n == 3){
a=$1
}
if(n == 4){
b=$2
}
if(n == 5){
c_ax=$3
}

}

cmd="grep Step "ARGV[1]" | wc -l"
while(cmd|getline){
steps=$1
}
close(cmd)

cmd="cat "ARGV[1]
while(cmd|getline){
 if($1 == "Step:"){
 c=0
 }
 c++
 if(c == 6){
  print $1
  print "Lattice=\""a" 0.0 0.0 0.0 "b" 0.0 0.0 0.0 "c_ax"\" Properties=species:S:1:pos:R:3 pbc=\"T T T\""
 }
 if(c > 6){
 if($1 == 3){
 $1="Li"
 }
 if($1 == 43){
 $1="Tc"
 }
 if($1 == 45){
 $1="Rh"
 }
 if($1 == 107){
 $1="V"
 }
 if($1 == 25){
 $1="Mn"
 }
 print $1,$3,$4,$5
 }
}
close(cmd)

}
